### ISSUE TITLE
PubSub: Deadlocks with nested Subscriber

### ISSUE THREAD

**Issue by ZeeD** [googleapis/java-pubsub#26] opened 2019-09-16 06:57 UTC
Can I "nest" subscribers?
Let's say I have this application, with a "main" `subscriber`, always listening; and in the `receiver` I create a new `subscriber` (for another subscription), with an `awaitTerminated` with a timeout.
Not always, but some times the application remain "stuck"; when this happen it's in the  `awaitTerminated`.
is there a way to debug this problem?
BTW: it's more common to get stuck if I run the code on kubernets than on my developer pc...

**Comment by dmitry-fa** [comment] 2019-12-26 13:54
I'm trying to reproduce the issue but I can't. So, either the issue is gone since that time, or we need more info regarding the way how do you get into the "deadlock":
- how do you start/stop subscribers
- which messages do you send and how often

> is there a way to debug this problem?
you can use: [jstack](https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/tooldescr016.html) command: `jstack -l <pid>`, where `<pid>` is your java process id

**Comment by hannahrogers-google** [comment] 2020-03-21 17:53
I tried reproducing this issue, but was unable to do so. 

It is possible that this was happening because of a bug that has now been fixed (#22), in which threads were not shut down properly when a stopping a Subscriber.

I am going to close this issue, as I am unable to reproduce. We can re-open if this issue is seen again.

**Closed by hannahrogers-google** 2020-03-21 17:53 UTC
Labels: :rotating_light:, api: pubsub, priority: p2, type: bug
