### ISSUE TITLE
Upgrade to netty-shaded version 1.28.1 causes failure when using topic-admin-client

### ISSUE THREAD

**Issue by kimcs** [googleapis/java-pubsub#190] opened 2020-05-18 09:26 UTC
#### Environment details

1. PubSub
2. MacOS 10.15.4
3. Java version zulu openjdk 11.0.3:
4. Bug introduced in com.google.cloud:google-cloud-pubsub:1.104.1
5. Run against pubsub emulator locally

The bug is caused by changing io.grpc:grpc-netty-shaded:jar from version 1.27.2 to 1.28.1

#### Steps to reproduce

  1. Create a maven project with a single dependency on com.google.cloud:google-cloud-pubsub:1.104.1 or higher
  2. Run the code example included below
  3. Observe the exception in the NettyClientStream static initializer: Exception in thread "grpc-default-executor-0" java.lang.NoSuchFieldError: NETTY_SHADED

### Workaround
Either use pubsub 1.104.0 or older, or downgrade io.grpc:grpc-netty-shaded to version 1.27.2

#### Code example

```java
import com.google.api.gax.core.NoCredentialsProvider;
import com.google.api.gax.grpc.GrpcTransportChannel;
import com.google.api.gax.rpc.FixedTransportChannelProvider;
import com.google.cloud.pubsub.v1.TopicAdminClient;
import com.google.cloud.pubsub.v1.TopicAdminSettings;
import com.google.pubsub.v1.ListTopicsRequest;
import com.google.pubsub.v1.ProjectName;
import io.grpc.ManagedChannelBuilder;

import java.io.IOException;

public class Test {

    public static void main(String[] args) throws IOException {
        try (TopicAdminClient topicAdminClient = TopicAdminClient.create(TopicAdminSettings.newBuilder()
                .setTransportChannelProvider(
                        FixedTransportChannelProvider.create(
                                GrpcTransportChannel.create(
                                        ManagedChannelBuilder
                                                .forAddress("localhost", 8538)
                                                .usePlaintext()
                                                .build()
                                )
                        )
                )
                .setCredentialsProvider(NoCredentialsProvider.create())
                .build())) {

            topicAdminClient.listTopics(ListTopicsRequest.newBuilder()
                    .setProject(ProjectName.of("test").toString())
                    .setPageSize(25)
                    .build());
        }
    }
}
```

#### Stack trace
```
Exception in thread "grpc-default-executor-0" java.lang.NoSuchFieldError: NETTY_SHADED
	at io.grpc.netty.shaded.io.grpc.netty.NettyClientStream.<clinit>(NettyClientStream.java:59)
	at io.grpc.netty.shaded.io.grpc.netty.NettyClientTransport.newStream(NettyClientTransport.java:177)
	at io.grpc.internal.CallCredentialsApplyingTransportFactory$CallCredentialsApplyingTransport.newStream(CallCredentialsApplyingTransportFactory.java:117)
	at io.grpc.internal.ForwardingConnectionClientTransport.newStream(ForwardingConnectionClientTransport.java:49)
	at io.grpc.internal.InternalSubchannel$CallTracingTransport.newStream(InternalSubchannel.java:635)
	at io.grpc.internal.DelayedClientTransport$PendingStream.createRealStream(DelayedClientTransport.java:353)
	at io.grpc.internal.DelayedClientTransport$PendingStream.access$300(DelayedClientTransport.java:341)
	at io.grpc.internal.DelayedClientTransport$5.run(DelayedClientTransport.java:300)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by hannahrogers-google** [comment] 2020-07-09 20:51
Duplicate of https://github.com/grpc/grpc-java/issues/6982.  From this issue, it looks like grpc-api needs to be at least 1.29.0 if upgrading grpc-netty-shaded version to 1.28.0.  In google-cloud-pubsub version 1.104.1, grpc-api version was 1.28.1.  This has since been resolved - we upgraded to grpc-api version 1.29.0 in google-cloud-pubsub version 1.105.1.

In general, we recommend using one of our BOMs for dependency conflict resolution (com.google.cloud:libraries-bom): https://github.com/googleapis/java-pubsub#quickstart

**Closed by hannahrogers-google** 2020-07-09 20:51 UTC
Labels: api: pubsub, priority: p2, type: bug
