### ISSUE TITLE
Pub/Sub client doesn't reconnect in the event of an outage

### ISSUE THREAD

**Issue by meltsufin** [googleapis/java-pubsub#30] opened 2019-11-13 15:11 UTC
Originally posted on the Spring Cloud GCP issue tracker: https://github.com/spring-cloud/spring-cloud-gcp/issues/2031

@veereshwaran asked if it's expected behavior that after an outage like the one on Nov 11th applications are unable to re-establish connections to Pub/Sub and come back to healthy operation without a restart. Is this correct or is it a bug?

**Comment by veereshwaran** [comment] 2019-12-25 04:35
Today I found another issue in my local-machine similar to above issue.

I run my mp-application which is listening to Pub/Sub topic. After application started events are received  from Pub/Sub subscription. 

During application running, my internet connection goes down and come-back again. After this internet problem, my application stopped to receive the message from Pub/Sub subscription.

**Comment by meltsufin** [comment] 2019-12-27 15:28
@chingor13 I don't think that "question" is the right labeling for this issue. Can it be reconsidered as a feature request or bug? Thanks!

**Comment by hannahrogers-google** [comment] 2020-01-09 19:40
@veereshwaran, do you have a log from when this issue happened that you could provide to us?

This is not expected behavior - we would expect for connections to come back eventually because we attempt to reconnect on most errors.

I can try reproducing this in the meantime while waiting for a log.

**Comment by veereshwaran** [comment] 2020-01-10 03:10
Hi @hannahrogers-google, 

When I running my application as a docker container, having a connectivity issue.

But If I run a jar file directly from my host machine doesn't have this connectivity issues.

I have attached docker-container logs below


![Screenshot from 2020-01-10 08-29-57](https://user-images.githubusercontent.com/20137083/72122627-8c412280-3384-11ea-867c-136667c75771.png)

**Comment by hannahrogers-google** [comment] 2020-01-13 21:04
Thanks @veereshwaran, 

Could you provide the entire log output? I am not seeing any error messages in the above log, just that no messages have been received during those 2 seconds.

**Comment by veereshwaran** [comment] 2020-01-14 06:57
Hi @hannahrogers-google,

Actually, I could not able to found any error logs. Only above debug log is loading.

The time displayed in above logs, at the same time, I published a message in respective Pub/Sub topic.


Could you try to run your code from docker container?

Because I am having a connectivity problem when I run my application as a docker-container.

**Comment by meltsufin** [comment] 2020-01-14 14:43
@veereshwaran Are you able to try a newer version of the project - `1.2.1.RELEASE`?
It contains numerous enhancement and bug fixes for Pub/Sub.

**Comment by veereshwaran** [comment] 2020-01-20 02:08
Sorry for the delayed response. Actually I was in festival vacation.

@meltsufin, I tried new version of Spring cloud Pub/Sub 1.2.1.RELEASE. My problem was resolved in this version.

The connectivity re-established again with respective stream(Pub/Sub subscription), but it will wait 5 mins to attempt reconnect.

**Comment by meltsufin** [comment] 2020-01-21 15:05
@veereshwaran Thanks for the update. The 5 mins might be due to exponential back-off. @hannahrogers-google Any thoughts on this?

**Comment by hannahrogers-google** [comment] 2020-01-28 14:08
Yes, we will initially wait 100ms before attempting to reconnect a subscriber stream.  If the stream continues to fail, we will double the amount of time that we wait before each attempt to reconnect (up to a certain max time).

@veereshwaran, have you had any more issues where the subscriber does not reconnect at all?

**Comment by veereshwaran** [comment] 2020-01-29 10:48
No @hannahrogers-google

**Closed** 2020-01-29 14:28 UTC
Labels: priority: p2, type: bug
