### ISSUE TITLE
Support the use of `PUBSUB_EMULATOR_HOST` with the P/S Emulator

### ISSUE THREAD

**Issue by anguillanneuf** [googleapis/java-pubsub#914] opened 2021-11-11 23:26 UTC
When using the P/S Java client lib with the P/S emulator, one is required to patch their code as describe [here](https://cloud.google.com/pubsub/docs/emulator#accessing_environment_variables). 

Ideally, the library should look for the environment variable `PUBSUB_EMULATOR_HOST` to determine whether to use emulated or real service.

Go/Node.js/PHP/Python/Ruby already support the use of an environment variable, which is a much more desirable experience when testing out P/S locally.

See internal b/206034017.

**Comment by hannahrogers-google** [comment] 2021-11-16 16:06
Closing as a duplicate of #308

**Closed by hannahrogers-google** 2021-11-16 16:06 UTC
Labels: type: feature request, api: pubsub
