### ISSUE TITLE
Receiver class io.grpc.netty.shaded.io.grpc.netty.NettyClientTransport does not define or inherit an implementation of the resolved method 'abstract io.grpc.internal.ClientStream newStream(io.grpc.MethodDescriptor, io.grpc.Metadata, io.grpc.CallOptions, io.grpc.ClientStreamTracer[])' of interface io.grpc.internal.ClientTransport

### ISSUE THREAD

**Issue by lpellegr** [googleapis/java-pubsub#903] opened 2021-11-08 16:33 UTC
Using `com.google.cloud:google-cloud-pubsub:1.114.7` in a Spring Boot (version 2.5.6) application with Java 17 throws this error upon subscription and handling of messages:

> Exception in thread "grpc-default-executor-0" java.lang.AbstractMethodError: Receiver class io.grpc.netty.shaded.io.grpc.netty.NettyClientTransport does not define or inherit an implementation of the resolved method 'abstract io.grpc.internal.ClientStream newStream(io.grpc.MethodDescriptor, io.grpc.Metadata, io.grpc.CallOptions, io.grpc.ClientStreamTracer[])' of interface io.grpc.internal.ClientTransport.
> 	at io.grpc.internal.MetadataApplierImpl.apply(MetadataApplierImpl.java:74)
> 	at io.grpc.CallCredentials2$1.apply(CallCredentials2.java:61)
> 	at io.grpc.auth.GoogleAuthLibraryCallCredentials$1.onSuccess(GoogleAuthLibraryCallCredentials.java:133)
> 	at com.google.auth.oauth2.OAuth2Credentials$FutureCallbackToMetadataCallbackAdapter.onSuccess(OAuth2Credentials.java:549)
> 	at com.google.auth.oauth2.OAuth2Credentials$FutureCallbackToMetadataCallbackAdapter.onSuccess(OAuth2Credentials.java:540)
> 	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1080)
> 	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
> 	at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:141)
> 	at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:130)
> 	at com.google.common.util.concurrent.ListenableFutureTask.done(ListenableFutureTask.java:107)
> 	at java.base/java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
> 	at java.base/java.util.concurrent.FutureTask.set(FutureTask.java:232)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:272)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
> 	at java.base/java.lang.Thread.run(Thread.java:833)

Downgrading to `com.google.cloud:google-cloud-pubsub:1.114.6` solves the issue.

**Comment by hannahrogers-google** [comment] 2021-11-09 19:30
Hi @lpellegr,

Are you using maven or gradle? And are you using a google-cloud-libraries BOM (https://github.com/GoogleCloudPlatform/cloud-opensource-java/wiki/The-Google-Cloud-Platform-Libraries-BOM)?

Can you share your dependency tree?

**Comment by lpellegr** [comment] 2021-11-09 21:30
@hannahrogers-google Thanks for your answer. 

I am using Gradle 7.2. No google-cloud-libraries BOM is used directly. Here are the dependencies:

https://gist.github.com/lpellegr/f6cc11802b8d6c254b5d4d9b034de364

**Comment by hannahrogers-google** [comment] 2021-11-10 15:10
Thanks for providing that info! I am trying to reproduce this issue, can you share steps to reproduce? How are you configuring the Subscriber, and when do you see this error (upon creating the subscriber, upon starting the subscriber, etc.)?

**Comment by knyttl** [comment] 2021-12-03 20:13
This happens to me too. I can see this error when trying to publish a message from Google Cloud Function.

I downgraded to `1.114.6` and it seems to be fine now.

**Comment by hannahrogers-google** [comment] 2022-01-20 16:37
I am seeing dependency conflicts in the dependency tree that you provided. Specifically:

io.grpc:grpc-core:1.39.0 -> 1.41.0
io.grpc:grpc-protobuf:1.39.0 -> 1.41.0
io.grpc:grpc-context:1.39.0 -> 1.41.0
io.grpc:grpc-api:1.39.0 -> 1.41.0
io.grpc:grpc-stub:1.39.0 -> 1.41.0

It looks like the NettyClientTransport class has changed between grpc versions 1.39.0 to 1.41.0. It looks like this specific change may be causing the dependency conflict: https://github.com/grpc/grpc-java/pull/8355. A fourth argument has been added to the newStream implementation.

For resolving dependency conflicts we typically recommend using a google-cloud-libraries BOM. Please find instructions here: https://cloud.google.com/java/docs/bom

If you are still running into issues after resolving the dependency conflicts, please let me know.

**Closed by hannahrogers-google** 2022-01-20 16:37 UTC
Labels: type: bug, priority: p2, api: pubsub
