### ISSUE TITLE
Unable to ack "big" pubsub messages (>5mb) 

### ISSUE THREAD

**Issue by blacar** [googleapis/java-pubsub#416] opened 2020-10-30 17:49 UTC
#### Environment details

1. Specify the API at the beginning of the title (for example, "BigQuery: ...")
   General, Core, and Other are also allowed as types

PubSub

2. OS type and version:

Dockerized Java pod running on GKE

3. Java version:

11

4. google-cloud-java version(s):

spring-boot 2.2.10
spring-cloud-gcp-pubsub 1.2.5
google-cloud-pubsub 1.108.0
google-cloud-core 1.93.7
gax 1.57.1
grpc-core 1.30.2

#### Steps to reproduce

  1. Send a big message to pubsub (>5Mb)
  2. Consume it.

#### Stack trace
There is no stacktrace. No exceptions. No error level messages.

#### External references such as API reference guides used	

https://spring.io/guides/gs/messaging-gcp-pubsub/

#### Any additional information below	

When trying to consume big messages from pubsub using refered stack, I cant.
1º Message never reaches my listener code
2º I get "Received data on closed stream" INFO message
3º PubSub keeps sending the message to my service (sent count metric keeps going) but message is never acked, never dequed, never dlq-ed, and never reaching my code (dumb log)

This might be related to 
https://github.com/googleapis/google-cloud-java/issues/2668

Thanks!

**Comment by hannahrogers-google** [comment] 2021-05-04 15:09
Thanks for reporting this, I will take a look at this issue. Are you observing this issue using synchronous pull or streaming pull?

**Comment by testower** [comment] 2021-05-06 12:25
We are facing this same issue, using streaming pull.

**Comment by hannahrogers-google** [comment] 2021-05-06 16:49
Thanks @testower, I will try reproducing this issue - what java client library version are you running with?

**Comment by hannahrogers-google** [comment] 2021-05-13 17:41
Thanks! We are working on creating a fix for this issue - stay tuned

**Comment by hannahrogers-google** [comment] 2021-09-21 21:32
I was able to reproduce this same issue overriding the defaultTransportChannelProvider. Ex.

```
Subscriber subscriber = Subscriber.newBuilder(subscription, receiver)
        .setChannelProvider(
            InstantiatingGrpcChannelProvider.newBuilder()
                .setKeepAliveTime(Duration.ofMinutes(5))
                .build())
        .build();
```

If a custom channel provider is provided, and the maxInboundMessageSize is not set (using 'setMaxInboundMessageSize'), the grpc maxInboundMessageSize defaults to 4mb, and you will see the 'Received data on closed stream' error if attempting to consume a message >4mb. The default channel provider in our client library uses a maxInboundMessageSize of 20mb (the max message size allowed).

I am going to mark this as resolved, as I cannot reproduce this issue using the default transport channel provider in our client library.

**Closed by hannahrogers-google** 2021-09-21 21:32 UTC
Labels: needs more info, type: bug, api: pubsub, priority: p3
